sudo: required
language: perl
perl:
  - "5.16"

matrix:
    include:
      - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
                packages:
                    - gcc-5
                    - g++-5
        env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#cache:
#  apt: true

before_install:
  - eval "${MATRIX_EVAL}"
  - which gcc
  - gcc -v
  - which g++
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - which gcc
  - gcc -v
  - which g++

install:
  - ./INSTALL.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - PWD=$(pwd)
  - sh test/TestAll.sh
  - cover -test

after_success:
  - cover -report codecov