sudo: required
language: perl
perl:
  - "5.16"

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#cache:
#  apt: true

before_install:
    - eval "${MATRIX_EVAL}"
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

install:
  - ./INSTALL.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - PWD=$(pwd)
  - sh test/TestAll.sh
  - cover -test

after_success:
  - cover -report codecov