sudo: false
language: perl

perl:
  - "5.16"

cache:
  apt: true

install:
  - ./INSTALL.sh

script:
  - PWD=$(pwd)
  - REPWD=$(sed 's/\//\\\//g' <<< $PWD | sed 's/\-/\\\-/g')
  - sed -i "s/test/$REPWD\/test/g" test/phame.ctl
  - perl src/runPhaME.pl test/phame.ctl

